"""
check_ingredient_signal.py
--------------------------
Question we are answering:

    For a fixed (wine, food_category) pair, does pairing_quality VARY by the
    specific food_item, or is it CONSTANT within the category?

Why it matters:
    The pairing dataset was generated by category-level rules ("acidic wine
    balances acidic food"). If quality is fully determined by food_category,
    then training an ingredient->wine model can only RE-LEARN the category map
    (a lossy copy of the rules). If quality varies WITHIN a category for the
    same wine, there is genuine sub-category / ingredient signal worth learning.

How we test it:
    Group rows by (wine_type, food_category). Inside each group, look at how
    many distinct pairing_quality values appear across the different food_items.
        - spread == 1  -> constant: category fully decides quality (NO signal)
        - spread  > 1  -> varies:   something below the category matters (SIGNAL)
    We report what fraction of groups vary, and show concrete examples.

Run:
    python -m data.wine.check_ingredient_signal
"""

from __future__ import annotations

import collections
import csv
import statistics
from pathlib import Path

CSV = Path("data/wine/wine_food_pairings.csv")


def main() -> None:
    rows = list(csv.DictReader(CSV.open(encoding="utf-8")))
    print(f"loaded {len(rows):,} rows\n")

    # group[(wine_type, food_category)] = list of (food_item, quality)
    groups: dict[tuple[str, str], list[tuple[str, int]]] = collections.defaultdict(list)
    for r in rows:
        key = (r["wine_type"], r["food_category"])
        groups[key].append((r["food_item"], int(r["pairing_quality"])))

    # only groups that actually contain >1 distinct food_item can possibly vary
    multi_item = {k: v for k, v in groups.items()
                  if len({fi for fi, _ in v}) > 1}

    print(f"{len(groups):,} (wine x food_category) groups total")
    print(f"{len(multi_item):,} of them contain more than one distinct food_item")
    print("  (only these can reveal within-category variation)\n")

    varying = 0
    spreads = []          # max-min quality within each multi-item group
    examples = []
    for key, items in multi_item.items():
        # for each distinct food_item, its quality values
        by_item = collections.defaultdict(list)
        for fi, q in items:
            by_item[fi].append(q)
        # does quality differ ACROSS food_items in this group?
        item_means = {fi: statistics.mean(qs) for fi, qs in by_item.items()}
        spread = max(item_means.values()) - min(item_means.values())
        spreads.append(spread)
        if spread > 0:
            varying += 1
            if len(examples) < 8 and spread >= 1:
                examples.append((key, sorted(item_means.items(),
                                             key=lambda x: x[1])))

    pct = 100 * varying / len(multi_item) if multi_item else 0
    print("=" * 60)
    print(f"RESULT: {varying:,} / {len(multi_item):,} groups "
          f"({pct:.1f}%) vary by food_item")
    print(f"        mean within-group quality spread: "
          f"{statistics.mean(spreads):.2f} (0 = no signal)")
    print(f"        max  within-group quality spread: {max(spreads):.2f}")
    print("=" * 60)

    if examples:
        print("\nexamples of within-category variation "
              "(same wine, same category, quality differs by item):\n")
        for (wine, cat), item_means in examples:
            print(f"  {wine}  x  {cat}:")
            for fi, m in item_means:
                print(f"        {m:.1f}   {fi}")
            print()


if __name__ == "__main__":
    main()
